### ISSUE TITLE
Wiki link class has changed to wiki-page

### ISSUE THREAD

**Issue by Fonant** [Undev/redmine_open_links_in_new_window#6]
This plugin needs some updates to work with current Redmine 2.6.0 because the Wiki links now have class "wiki-page" and not "wiki-anchor".

**Comment by akzhan** [comment]
unfortunately, the company Undev was closed in 2015

**Comment by Fonant** [comment]
For reference, there's a quite simple patch for Redmine to do this here:
https://www.redmine.org/issues/3801
